### ISSUE TITLE
[Help] Types issue with monorepo and SvelteKit (Svelte 5)

### ISSUE THREAD

**Issue by Extarys** [ap0nia/eden-query#38]
**What it's doing**

I use sveltkit for the ui and elysia for the api in a monorepo.

Importing the types from elysia to svelte gives types error:
```
export const eden = createEdenTreatySvelteQuery<ElysiaAppTypes>()
                                                      ^
Type 'Elysia<"", false, { decorator: {}; store: {}; derive: {}; resolve: {}; }, { type: {}; error: {}; }, { schema: {}; macro: {}; macroFn: {}; },
{ index: { get: { body: unknown; params: {}; query: unknown; headers: unknown; response: { 200: { res: string; }; }; }; }; } & { ...; },
{ ...; }, { ...; }>' does not satisfy the constraint 'Elysia<any, any, any, any, any, any, any, any>'.
  Types have separate declarations of a private property 'dependencies'.ts(2344)
```

**What's expected**
Types should work

Didn't test after that, as I get `TypeError: rootHooks[hook] is not a function`  from the ui, but it might be caused by the type error ? Not sure how to make the query either I might have made a mistake there too.

I tested:
`const postQuery = eden.posts.get.useQuery({ postId: 'id_bilbo' });`
`const postQuery = eden.api.posts.get.useQuery({ postId: 'id_bilbo' });`

Reproduction repo: https://codeberg.org/Dreamboat9222/mono-test-elysia-eden-svelte

**Comment by ap0nia** [comment]
## `rootHooks[hook]`
I can fix this issue today. 

## Elysia types
It looks like you have [elysia@1.1.19 installed](https://codeberg.org/Dreamboat9222/mono-test-elysia-eden-svelte/src/commit/ca01b5389ad3fea37c0f4e6aacb65c1235266fb2/backends/api-app/package.json#L12). 

The upstream types change very frequently, and this library has currently pinned `elysia@1.1.6` as the peer dependency.

## Next Steps
The reason why the elysia types are important is because this library supports type-safety on the type-level for the batch and transform plugins. If you try to use either without adding the plugin to the server, then the client will show a type-error. Alternative approaches:
1. I could remove this type-checking altogether, so the changes in upstream types are less impactful.
2. I could export an untyped client that doesn't depend on the elysia types as closely.

**Comment by ap0nia** [comment]
It's really not, it's just that the specific types I refer to in order to add the type-safety happen to change frequently. And I happen to be building a project using `elysia@1.1.6` so I just left it pinned there out of personal interests 🤓

**Comment by ap0nia** [comment]
I've disabled type-checking for the default `links`, so it would be easier to integrate with different `elysia` versions. I've also upgraded to `elysia@1.1.19` across the monorepository.

**Comment by ap0nia** [comment]
I can take care of the issues. Yes, please open new issues if you happen to encounter them.
