### ISSUE TITLE
No type inference when using the autoload plugin

### ISSUE THREAD

**Issue by Extarys** [ap0nia/eden-query#45]
**Alternative title: Automagically infer types when using the autoload plugin**
That one might be tricky.

## Actual behaviour

Eden only sees the routes used directly from other imported instances.

# Desired behaviour
Imported routes by autoload should be picked up by eden-query.
**To be fair, that is also probably a treaty issue - Should I open a feature suggestion over there?**

# Workaround
What I currently do it:
```
	.use(
		await autoload({
			types: { useExport: true, output: "./types-routes-1.ts" },
			dir: "./routes/authentication",
			prefix: "/authentication",
		}),
	)
	.use(isAuthenticated)
	.use(
		await autoload({
			types: { useExport: true, output: "./types-routes-2.ts" },
			dir: "./routes/Protected",
			prefix: "/",
		}),
	)
	.use(secret)
	.use(
		await autoload({
			types: { useExport: true, output: "./types-routes-3.ts" },
			dir: "./routes/secret",
			prefix: "/secret",
		}),
	)

...
import { type App } from "./app";
import { type Routes as r1 } from "./types-routes-1";
import { type Routes as r2 } from "./types-routes-2";
import { type Routes as r3 } from "./types-routes-3";
export type Routes = App & r1 & r2 & r3;
```

I then use that `Routes` type for Eden/Treaty.

(Note that I suggested to the autoload plugin maintainer to allow easily adding middleware/plugins to specific routes as a config to autoload, so the types may change if they decide to implement something like that eventually)

**Comment by ap0nia** [comment]
Yes, I think you should also discuss this with the official sources.

Eden works by introspecting the `Elysia['_routes']` property. You can preview it like so:

```ts
import { Elysia } from 'elysia'

const base = new Elysia()

type Base = typeof base['_routes']
//      ^? {}  This should be empty right now

const withHello = base.get('/hello', async () => 'hello')

type WithHello = typeof withHello['_routes']
//      ^? {  hello: { get: { response: { 200: string }, /** other properties... */ } } }
```

You could observe that calling methods will update the internal `_routes` type on the `elysia` instance. Although I do not have experience with this plugin, I suspect that `autoload` does not do update the `_routes` type automatically because it is dynamic in nature.

This behavior is inherent to Eden's strategy as a whole, so the reason why compiling the types would work is because Eden has something to parse. I don't expect this to change unless TS or Eden provide a way to introspect files directly. I know that `sveltekit` has a custom `typescript-svelte-plugin` that seems to do this...
